# Generated by Django 3.2.5 on 2022-02-05 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20220204_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.category')),
                ('employeeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.employee')),
            ],
            options={
                'verbose_name': 'EmpleadoCateg',
                'verbose_name_plural': 'EmpleadosCategs',
                'db_table': 'empleadocat',
                'ordering': ['id'],
            },
        ),
    ]
